import {
  LayoutDashboard,
  BookOpen,
  FolderTree,
  Warehouse,
  FileCheck,
  FileX,
  Bookmark,
  Receipt,
  Users,
  BarChart3,
  Bell,
  History,
  Settings
} from 'lucide-react';

export const NAVIGATION_ITEMS = [
  // MAIN
  { name: 'Dashboard', path: '/librarian/dashboard', icon: LayoutDashboard, category: 'Main' },
  
  // CATALOGUE
  { name: 'Book Directory', path: '/librarian/books', icon: BookOpen, category: 'Catalogue' },
  { name: 'Book Categories', path: '/librarian/categories', icon: FolderTree, category: 'Catalogue' },
  { name: 'Inventory Management', path: '/librarian/inventory', icon: Warehouse, category: 'Catalogue' },
  
  // CIRCULATION
  { name: 'Issue Book', path: '/librarian/issue', icon: FileCheck, category: 'Circulation' },
  { name: 'Return Book', path: '/librarian/return', icon: FileX, category: 'Circulation' },
  { name: 'Reservations', path: '/librarian/reservation', icon: Bookmark, category: 'Circulation' },
  { name: 'Fine Management', path: '/librarian/fines', icon: Receipt, category: 'Circulation' },
  
  // MEMBERS
  { name: 'Members Directory', path: '/librarian/members', icon: Users, category: 'Members' },
  
  // SYSTEM
  { name: 'Reports & Analytics', path: '/librarian/reports', icon: BarChart3, category: 'System' },
  { name: 'Audit Logs', path: '/librarian/audit', icon: History, category: 'System' },
  { name: 'Notifications', path: '/librarian/notifications', icon: Bell, category: 'System' },
  { name: 'Library Settings', path: '/librarian/settings', icon: Settings, category: 'System' }
];

export const MOCK_BOOKS = [
  {
    id: 'BK-001',
    bookCode: 'GFS-BK-001',
    title: 'Introduction to Physics (Vol 1)',
    isbn: '978-0-19-563534-0',
    barcode: '9780195635340',
    author: 'H.C. Verma',
    publisher: 'Bharati Bhawan',
    edition: '2nd',
    publicationYear: 2019,
    language: 'English',
    category: 'Science',
    subject: 'Physics',
    rackNumber: 'R-04',
    shelfNumber: 'S-12',
    bookCost: 350,
    purchaseDate: '2023-05-10',
    supplier: 'National Book Depot',
    status: 'Available',
    totalCopies: 5,
    availableCopies: 3,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-002',
    bookCode: 'GFS-BK-002',
    title: 'A Brief History of Time',
    isbn: '978-0-553-38016-3',
    barcode: '9780553380163',
    author: 'Stephen Hawking',
    publisher: 'Bantam Books',
    edition: '10th Anniv.',
    publicationYear: 1998,
    language: 'English',
    category: 'Science',
    subject: 'Cosmology',
    rackNumber: 'R-04',
    shelfNumber: 'S-13',
    bookCost: 499,
    purchaseDate: '2024-02-15',
    supplier: 'Oxford University Press',
    status: 'Available',
    totalCopies: 3,
    availableCopies: 2,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-003',
    bookCode: 'GFS-BK-003',
    title: 'Higher Algebra',
    isbn: '978-93-5140-083-7',
    barcode: '9789351400837',
    author: 'Hall & Knight',
    publisher: 'Arihant Publications',
    edition: '1st',
    publicationYear: 2016,
    language: 'English',
    category: 'Mathematics',
    subject: 'Algebra',
    rackNumber: 'R-02',
    shelfNumber: 'S-01',
    bookCost: 280,
    purchaseDate: '2022-09-01',
    supplier: 'S. Chand & Co.',
    status: 'Available',
    totalCopies: 8,
    availableCopies: 6,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-004',
    bookCode: 'GFS-BK-004',
    title: 'Organic Chemistry',
    isbn: '978-0-13-407458-0',
    barcode: '9780134074580',
    author: 'Paula Y. Bruice',
    publisher: 'Pearson Education',
    edition: '8th',
    publicationYear: 2016,
    language: 'English',
    category: 'Science',
    subject: 'Chemistry',
    rackNumber: 'R-04',
    shelfNumber: 'S-10',
    bookCost: 950,
    purchaseDate: '2023-11-20',
    supplier: 'Pearson India',
    status: 'Available',
    totalCopies: 4,
    availableCopies: 2,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-005',
    bookCode: 'GFS-BK-005',
    title: 'Wings of Fire',
    isbn: '978-81-7371-146-6',
    barcode: '9788173711466',
    author: 'A.P.J. Abdul Kalam',
    publisher: 'Universities Press',
    edition: '1st',
    publicationYear: 1999,
    language: 'English',
    category: 'Biography',
    subject: 'Autobiography',
    rackNumber: 'R-01',
    shelfNumber: 'S-05',
    bookCost: 325,
    purchaseDate: '2021-06-18',
    supplier: 'National Book Depot',
    status: 'Issued',
    totalCopies: 2,
    availableCopies: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-006',
    bookCode: 'GFS-BK-006',
    title: 'Merchant of Venice',
    isbn: '978-0-19-832145-3',
    barcode: '9780198321453',
    author: 'William Shakespeare',
    publisher: 'Oxford University Press',
    edition: 'Revised',
    publicationYear: 2014,
    language: 'English',
    category: 'Literature',
    subject: 'Drama',
    rackNumber: 'R-03',
    shelfNumber: 'S-04',
    bookCost: 195,
    purchaseDate: '2023-01-10',
    supplier: 'Oxford University Press',
    status: 'Available',
    totalCopies: 10,
    availableCopies: 9,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-007',
    bookCode: 'GFS-BK-007',
    title: 'Discovery of India',
    isbn: '978-0-14-303103-1',
    barcode: '9780143031031',
    author: 'Jawaharlal Nehru',
    publisher: 'Penguin Books',
    edition: 'Centenary Edition',
    publicationYear: 2004,
    language: 'English',
    category: 'History',
    subject: 'Indian History',
    rackNumber: 'R-05',
    shelfNumber: 'S-02',
    bookCost: 450,
    purchaseDate: '2022-04-12',
    supplier: 'National Book Depot',
    status: 'Available',
    totalCopies: 3,
    availableCopies: 1,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-008',
    bookCode: 'GFS-BK-008',
    title: 'Computer Science with Python',
    isbn: '978-93-89656-78-4',
    barcode: '9789389656784',
    author: 'Sumita Arora',
    publisher: 'Dhanpat Rai & Co.',
    edition: '2024',
    publicationYear: 2024,
    language: 'English',
    category: 'Technology',
    subject: 'Computer Science',
    rackNumber: 'R-06',
    shelfNumber: 'S-08',
    bookCost: 595,
    purchaseDate: '2024-03-01',
    supplier: 'Dhanpat Rai Pub',
    status: 'Available',
    totalCopies: 15,
    availableCopies: 12,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-009',
    bookCode: 'GFS-BK-009',
    title: 'Principles of Economics',
    isbn: '978-0-538-45305-9',
    barcode: '9780538453059',
    author: 'N. Gregory Mankiw',
    publisher: 'Cengage Learning',
    edition: '6th',
    publicationYear: 2011,
    language: 'English',
    category: 'Social Studies',
    subject: 'Economics',
    rackNumber: 'R-07',
    shelfNumber: 'S-03',
    bookCost: 890,
    purchaseDate: '2023-08-25',
    supplier: 'Pearson India',
    status: 'Available',
    totalCopies: 4,
    availableCopies: 4,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'BK-010',
    bookCode: 'GFS-BK-010',
    title: 'Panchatantra Tales',
    isbn: '978-81-7011-870-1',
    barcode: '9788170118701',
    author: 'Vishnu Sharma',
    publisher: 'Children Book Trust',
    edition: 'Repr.',
    publicationYear: 2018,
    language: 'Hindi / English',
    category: 'Fiction',
    subject: 'Fables',
    rackNumber: 'R-08',
    shelfNumber: 'S-01',
    bookCost: 120,
    purchaseDate: '2020-12-05',
    supplier: 'S. Chand & Co.',
    status: 'Available',
    totalCopies: 6,
    availableCopies: 5,
    schoolId: 'SCH-2026-09'
  }
];

export const MOCK_ISSUES = [
  {
    id: 'ISS-001',
    bookId: 'BK-001',
    bookTitle: 'Introduction to Physics (Vol 1)',
    bookCode: 'GFS-BK-001',
    memberId: 'STU-001',
    memberName: 'Arjun Sharma',
    memberType: 'Student',
    memberClass: 'Class X-A',
    issueDate: '2026-07-10',
    dueDate: '2026-07-24',
    returnDate: null,
    status: 'Issued',
    fineAmount: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'ISS-002',
    bookId: 'BK-005',
    bookTitle: 'Wings of Fire',
    bookCode: 'GFS-BK-005',
    memberId: 'STU-003',
    memberName: 'Karan Malhotra',
    memberType: 'Student',
    memberClass: 'Class IX-C',
    issueDate: '2026-06-25',
    dueDate: '2026-07-09',
    returnDate: null,
    status: 'Overdue',
    fineAmount: 16, // Calculated as: 8 days overdue * 2 INR/day
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'ISS-003',
    bookId: 'BK-003',
    bookTitle: 'Higher Algebra',
    bookCode: 'GFS-BK-003',
    memberId: 'TEA-001',
    memberName: 'Dr. Ramesh Prasad',
    memberType: 'Teacher',
    memberClass: 'Senior Faculty - Math',
    issueDate: '2026-07-01',
    dueDate: '2026-07-31',
    returnDate: null,
    status: 'Issued',
    fineAmount: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'ISS-004',
    bookId: 'BK-006',
    bookTitle: 'Merchant of Venice',
    bookCode: 'GFS-BK-006',
    memberId: 'STU-002',
    memberName: 'Priya Patel',
    memberType: 'Student',
    memberClass: 'Class XII-Sci',
    issueDate: '2026-07-05',
    dueDate: '2026-07-19',
    returnDate: '2026-07-15',
    status: 'Returned',
    fineAmount: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'ISS-005',
    bookId: 'BK-007',
    bookTitle: 'Discovery of India',
    bookCode: 'GFS-BK-007',
    memberId: 'STU-005',
    memberName: 'Sneha Roy',
    memberType: 'Student',
    memberClass: 'Class XI-Arts',
    issueDate: '2026-06-10',
    dueDate: '2026-06-24',
    returnDate: '2026-06-28',
    status: 'Returned',
    fineAmount: 8, // 4 days overdue, paid
    schoolId: 'SCH-2026-09'
  }
];

export const MOCK_FINES = [
  {
    id: 'FIN-001',
    issueId: 'ISS-005',
    memberId: 'STU-005',
    memberName: 'Sneha Roy',
    bookTitle: 'Discovery of India',
    fineType: 'Late Return',
    daysOverdue: 4,
    finePerDay: 2,
    totalFine: 8,
    paidAmount: 8,
    status: 'Paid',
    paymentDate: '2026-06-28',
    waiveReason: '',
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'FIN-002',
    issueId: 'ISS-002',
    memberId: 'STU-003',
    memberName: 'Karan Malhotra',
    bookTitle: 'Wings of Fire',
    fineType: 'Late Return',
    daysOverdue: 8,
    finePerDay: 2,
    totalFine: 16,
    paidAmount: 0,
    status: 'Unpaid',
    paymentDate: null,
    waiveReason: '',
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'FIN-003',
    issueId: 'ISS-009',
    memberId: 'STU-008',
    memberName: 'Rohan Verma',
    bookTitle: 'Organic Chemistry',
    fineType: 'Damaged Pages',
    daysOverdue: 0,
    finePerDay: 0,
    totalFine: 100,
    paidAmount: 0,
    status: 'Waived',
    paymentDate: null,
    waiveReason: 'Pages were already loose, approved by Principal',
    schoolId: 'SCH-2026-09'
  }
];

export const MOCK_MEMBERS = [
  {
    id: 'LMEM-001',
    memberId: 'STU-001',
    memberName: 'Arjun Sharma',
    memberType: 'Student',
    class: 'Class X-A',
    admissionNo: 'GFS-2024-001',
    membershipStatus: 'Active',
    booksIssued: 1,
    maxBooksAllowed: 3,
    pendingFines: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'LMEM-002',
    memberId: 'STU-002',
    memberName: 'Priya Patel',
    memberType: 'Student',
    class: 'Class XII-Sci',
    admissionNo: 'GFS-2023-112',
    membershipStatus: 'Active',
    booksIssued: 0,
    maxBooksAllowed: 3,
    pendingFines: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'LMEM-003',
    memberId: 'STU-003',
    memberName: 'Karan Malhotra',
    memberType: 'Student',
    class: 'Class IX-C',
    admissionNo: 'GFS-2025-054',
    membershipStatus: 'Suspended',
    booksIssued: 1,
    maxBooksAllowed: 3,
    pendingFines: 16,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'LMEM-004',
    memberId: 'TEA-001',
    memberName: 'Dr. Ramesh Prasad',
    memberType: 'Teacher',
    class: 'Senior Faculty - Math',
    admissionNo: 'EMP-T-023',
    membershipStatus: 'Active',
    booksIssued: 1,
    maxBooksAllowed: 7,
    pendingFines: 0,
    schoolId: 'SCH-2026-09'
  },
  {
    id: 'LMEM-005',
    memberId: 'TEA-002',
    memberName: 'Ms. Anjali Sen',
    memberType: 'Teacher',
    class: 'Faculty - English',
    admissionNo: 'EMP-T-087',
    membershipStatus: 'Active',
    booksIssued: 0,
    maxBooksAllowed: 7,
    pendingFines: 0,
    schoolId: 'SCH-2026-09'
  }
];

export const MOCK_RESERVATIONS = [
  {
    id: 'RES-001',
    bookId: 'BK-005',
    bookTitle: 'Wings of Fire',
    memberId: 'STU-002',
    memberName: 'Priya Patel',
    memberType: 'Student',
    reserveDate: '2026-07-12',
    status: 'Pending',
    queuePosition: 1
  },
  {
    id: 'RES-002',
    bookId: 'BK-005',
    bookTitle: 'Wings of Fire',
    memberId: 'STU-004',
    memberName: 'Vivek Mehta',
    memberType: 'Student',
    reserveDate: '2026-07-14',
    status: 'Pending',
    queuePosition: 2
  },
  {
    id: 'RES-003',
    bookId: 'BK-004',
    bookTitle: 'Organic Chemistry',
    memberId: 'TEA-002',
    memberName: 'Ms. Anjali Sen',
    reserveDate: '2026-07-16',
    status: 'Completed',
    queuePosition: 0
  }
];

export const MOCK_LOGS = [
  {
    id: 'LOG-001',
    timestamp: '2026-07-17T11:20:00Z',
    operatorName: 'Sanjay Kumar (Librarian)',
    action: 'Issued Book',
    details: 'Issued "Introduction to Physics (Vol 1)" to student Arjun Sharma (STU-001).'
  },
  {
    id: 'LOG-002',
    timestamp: '2026-07-17T10:45:00Z',
    operatorName: 'Sanjay Kumar (Librarian)',
    action: 'Collected Fine',
    details: 'Collected Late Return fine of INR 8 from Sneha Roy (STU-005).'
  },
  {
    id: 'LOG-003',
    timestamp: '2026-07-16T15:30:00Z',
    operatorName: 'Sanjay Kumar (Librarian)',
    action: 'Added Book',
    details: 'Added 5 new copies of "Computer Science with Python" (BK-008) to Rack R-06, S-08.'
  },
  {
    id: 'LOG-004',
    timestamp: '2026-07-15T09:12:00Z',
    operatorName: 'Sanjay Kumar (Librarian)',
    action: 'Updated Reservation',
    details: 'Reservation status updated to Completed for book "Organic Chemistry" (BK-004) for member Ms. Anjali Sen.'
  }
];

export const MOCK_CATEGORIES = [
  { name: 'Science', bookCount: 15, subCategories: ['Physics', 'Chemistry', 'Biology'] },
  { name: 'Mathematics', bookCount: 8, subCategories: ['Algebra', 'Geometry', 'Calculus'] },
  { name: 'Literature', bookCount: 12, subCategories: ['Drama', 'Poetry', 'Novels'] },
  { name: 'History', bookCount: 5, subCategories: ['Indian History', 'World History'] },
  { name: 'Technology', bookCount: 18, subCategories: ['Computer Science', 'Programming', 'AI'] },
  { name: 'Fiction', bookCount: 10, subCategories: ['Fables', 'Sci-Fi', 'Fantasy'] }
];
